# Generated by Django 4.1.3 on 2022-12-24 23:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('series', models.IntegerField(blank=True, null=True, verbose_name='card series')),
                ('number', models.CharField(max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='\\d{16}')], verbose_name='card number')),
                ('release_at', models.DateField(auto_now_add=True, verbose_name='release date')),
                ('expiration_at', models.DateField(verbose_name='expiration date')),
                ('status', models.CharField(choices=[('NotActive', 'Not Active'), ('Active', 'Active'), ('Blocked', 'Blocked'), ('Expired', 'Expired')], default='NotActive', max_length=10, verbose_name='status')),
                ('amount', models.FloatField(default=0, verbose_name='ammount')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='ammount')),
                ('buytime', models.DateTimeField(verbose_name='time')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
            ],
        ),
    ]
