# Generated by Django 4.1.3 on 2022-12-23 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.IntegerField(choices=[('1', 'Not Active'), ('2', 'Active'), ('3', 'Blocked'), ('4', 'Expired')], default='1', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='ammount'),
        ),
    ]
