# Generated by Django 4.1.3 on 2022-12-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_status_alter_purchase_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not Active'), (2, 'Active'), (3, 'Blocked'), (4, 'Expired')], default=1, verbose_name='status'),
        ),
    ]
